### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by cod3rguy** [cod3rguy/cod3rguy.github.io#4]
- [x] Add next and previous post buttons
- [x] Update footer and add links
- [x] Update pages with data
- [x] Update README
- [x] Add comment system (Disqus maybe?)
